name: ChatOps-DEPLOY

env:
  TEST: TEST

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/create')
    
    steps:

    - name: "Set env variables from chat message"
      run: |
        pattern="^\/create (\w+)$"
        [[ "${{ github.event.comment.body }}" =~ $pattern ]]
        echo ::set-env name=TAG::"${BASH_REMATCH[1]}"
        echo $TAG
        
    - name: Start creating cluster
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hey, @${{ github.event.comment.user.login }}!
          :rocket: Started new cluster with name ${{ env.TAG }} is beginning! :rocket:
      
    - name: setup cluster
      run: |
        echo "setting up ${TAG}"
        echo "setting up ${{ env.TAG }}"
        echo ::set-env name=OUTPUT::"test"

    - name: Create completed comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hey, @${{ github.event.comment.user.login }}!
          :tada: Cluster to ${{ env.TAG }} completed! :tada:
          You should be able to browse it at ${{ env.OUTPUT }}. Happy testing!
